[project]
name = "dohome_rgb"
authors = [
    {name = "Mikhael Khrustik", email = "misha@myrt.co"},
]
description = "DoHome lights Home Assistant integration"
readme = "README.md"
requires-python = ">=3.14.2"
keywords = ["home-assistant", "dohome"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "homeassistant>=2026.6.2",
    "dohome-api==2.2.1",
    "basedpyright>=1.39.7",
]
version = "v0.0.0"

[tool.basedpyright]
venvPath = "."
venv = ".venv"
reportSelfClsParameterName = false
reportUnannotatedClassAttribute = false
reportConstantRedefinition = false
reportExplicitAny = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportAny = false
reportMissingTypeStubs = false
